# Site settings
title: Boris Mühmer
email: boris.muehmer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  TBD: Write an awesome description!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bsmr.github.io" # the base hostname & protocol for your site
twitter_username: bsmuehmer
github_username:  bsmr

# Build settings
markdown: kramdown
